# Generated by Django 4.2.7 on 2023-11-17 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leave_application",
            old_name="bemployee_id",
            new_name="employee_id",
        ),
        migrations.RenameField(
            model_name="statud_leave_application",
            old_name="aemployee_id",
            new_name="employee_id",
        ),
    ]
