# Generated by Django 4.2.7 on 2023-11-17 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_rename_bemployee_id_leave_application_employee_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Statud_Leave_Application",
            new_name="Status_Leave_Application",
        ),
    ]
